### ISSUE TITLE
fixes to plotting function

### ISSUE THREAD

**Issue by mfisher5** [jameals/cciea_networks#11]
On the new `plotting` branch, I've created the function [plot_network_bulk_comparable_v2.R](https://github.com/jameals/cciea_networks/blob/plotting/R/plot_network_bulk_comparable_v2.R), which uses a rescaling function to adjust the node labels. 

I re-generated all of the network graphs from 02_plot_annual_networks_cciea.R into [this folder](https://github.com/jameals/cciea_networks/tree/plotting/data/networks/participation_vessel_ports/plots/comparable-labels).

Another adjustment to the label might be to put the vessel count at the center of the node, and then have the fishery name around the edge (instead of having both around the edge). For example: 
![img-1](https://github.com/jameals/cciea_networks/blob/plotting/data/networks/participation_vessel_ports/plots/comparable-labels/TEST_Puget%20Sound_2019_circular.png?raw=true)
![img-2](https://github.com/jameals/cciea_networks/blob/plotting/data/networks/participation_vessel_ports/plots/comparable-labels/TEST_Puget%20Sound_2020_circular.png?raw=true)

I haven't incorporated this into the new plotting function, but I can!

@jameals , can you take a look through the folder linked above and make sure you're happy with the new label positions? And then let me know if you want me to set the vessel counts into the middle of the nodes, or leave them where they are?

Then I'll incorporate those changes into the original plotting function, and create a pull request to the main branch.

**Comment by jameals** [comment]
@mfisher5 , thank you! these look great. i prefer your idea to set the vessel counts into the middle of the nodes. 2 pesky questions: (1) is there a reason the nodes tend to be concentrated between 9 o'clock and 3 o'clock on many networks? (2) did you play around with the node label font color matching the node color (worried that some colors would not show up nicely, but what do you think)?

ok, i lied 3rd Q. 
3) one concern i have is that the function is  plot_network_bulk_comparable_v2.R. "bulk" refers to the aggregate, port-level networks we made for the SSC-ES review this past summer. but i also see this note for "plot_network_bulk_comparable.R":

"note this script is flexible whether we want to plot vessel-level or aggregate (bulk) networks. simply change the file_suffix. similarly, it is flexible whether we want to plot port group or state networks, simply change how 'port_group' is defined based on unique(V(g)$p)"

so we are probably ok? if so, can you clarify a bit what is meant by changing file_suffix? My understanding is that that is simply the output image name.  is that correct? and if we wanted to report state-level networks, that is simply a matter of saving the state name in the igraph object under V(g)$p?

**Comment by mfisher5** [comment]
(1) yes! it's because of the way I specify the locations of the nodes across graphs, to make the networks visually comparable. The code first constructs a matrix of which graphs have which fisheries, and then pads each graph with the missing fisheries by appending blank nodes. Because the matrix is constructed by looping over each graph in the list, I think that to change where the nodes end up you could potentially re-arrange the order of the graphs in your input list (glist). However, you would have to be strategic about which graphs get put into the list first. I don't have a good way of ensuring that networks with a subset of all fisheries have their nodes equally spaced, while also being in the same location as in the other graphs.

(2) I added in a new argument `color_labels` to the plotting function *plot_comparable_networks* that makes it easy to switch between gray labels (`color_labels=FALSE`) or labels that are the same colors as the nodes (`color_labels=TRUE`). I think that the colors are a little too light for text; and for some of the large nodes (salmon especially), the labels overlap a tiny bit with the node itself, so when they are the same color they blend.

(3) we're ok! I adjusted the working in that comment, to clarify. and also renamed our updated plotting function / the .R script that holds the function to remove the reference to "bulk."

**Comment by jameals** [comment]
yeehaw, thank you @mfisher5 ! just so i am clear: did you update the code in the main branch, or just the plotting branch? if the latter, how do you recommend i grab the relevant new bits of code?

**Comment by mfisher5** [comment]
just in the plotting branch at the moment, but I created a merge request that will pull all the code into the main branch. It looks like there aren't any conflicts between the two branches, but I didn't want to automatically merge in case you had local changes that weren't on the main branch yet. 
So all you have to do is accept the merge request, and you should be good to go!
