### ISSUE TITLE
weirdness in making percent_boats ???

### ISSUE THREAD

**Issue by jameals** [jameals/cciea_networks#8]
@mfisher5 : is line 67 doing anything weird by dividing the year (or crab_year) by rowSums(boats, na.rm = T)?
generate_participation_network.R

**Comment by jameals** [comment]
@mfisher5 : also, in line 135 where network_fleet_size is calculated, does it ignore boats with a contribution of NA? if not, isn't this the same as fleet_size calculated in line 40?
generate_participation_network.R

**Comment by mfisher5** [comment]
I think that the `crab_year` column is removed from the `boats` data frame on line 57 (`boats$crab_year <- NULL`), because the crab year is incorporated into the row name. So when the `percent_boats` data frame is produced by `boats/rowSums(boats, na.rm = T)`, there isn't a year column getting divided

**Comment by mfisher5** [comment]
The `network_fleet_size` value should not include boats with a contribution of NA, and should only include boats that generate at least `min_rev`. 

But now that I'm looking back at the code, is it possible that when we apply the `min_rev_indiv` filter on line 70 
```
percent_boats_mat[which(boats<min_rev_indiv)] <- NA
```
we're zeroing out all fishery participation for a vessel? So we may need to add another line after line 71 (right before `rm(percent_boats_mat`) to remove boats that don't generate at least `min_rev` annually, as on line 60...
```
if(any(rowSums(percent_boats,na.rm=T)<min_rev)){percent_boats <- percent_boats[-which(rowSums(percent_boats, na.rm=T)<min_rev),]}
```

**Comment by jameals** [comment]
ok, i just checked into line 70 and it is not appear to zero out all fishery participation for a vessel. and i can see how it is not identical to fleet_size. so i am going to leave the code as is. thanks for chiming in!
